### ISSUE TITLE
Support for new User Interface API functionality

### ISSUE THREAD

**Issue by przemekrcloudity** [Ziemniakoss/lwc-typings-generator#5]
New wirable methods were added in latest release: https://help.salesforce.com/s/articleView?id=release-notes.rn_api_ui.htm&type=5&release=238

**Comment by Ziemniakoss** [comment]
Waitning for more info from SF side in [docs](https://developer.salesforce.com/docs/component-library/bundle/lightning-ui-related-list-api/documentation)

**Comment by Ziemniakoss** [comment]
Ok closing for now as we still don't have documentation available and this issue is distracting me. I Will reopen this issue when Salesforce finally publish documentation
